spring:
    datasource:
      url: jdbc:mysql://localhost/fsfuserdb
      username: fsfAdmin
      password: fsfPas
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          current_session_contextclass: org.springframework.orm.hibernate4.SpringSessionContext
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect