spring:
    datasource:
      url: jdbc:mysql://localhost/fsfuserdb
      username: fsfAdmin
      password: fsfPas
    jpa:
      hibernate:
        ddl-auto: create
security:
  user:
    name: fsf-persoon
    password: fsf-persoon-pw
  hibernate:
    current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8081